name: 'Heimdall Tools Action'
author: The MITRE Corporation
description: >
  Convert supported formats to Heimdall Data Format for use with any HDF-compatible viewer'
branding:
  icon: 'repeat'
  color: 'gray-dark'
inputs:
  file:
    description: 'File to convert into HDF'
    required: true
    deprecationMessage: 'THIS ACTION IS DEPRECATED. Use mitre/saf_action to replace this action. Find it here: https://github.com/marketplace/actions/saf-cli-action'
  converter:
    description: 'Specify which convert to use to convert <file-to-convert>'
    requried: true
    deprecationMessage: 'THIS ACTION IS DEPRECATED. Use mitre/saf_action to replace this action. Find it here: https://github.com/marketplace/actions/saf-cli-action'
outputs:
  hdf-output:
    description: 'HDF output of <file-to-convert>'
runs:
  using: 'docker'
  image: 'Dockerfile'
